config/routes.rb
Civicspaces::Application.routes.draw do
  devise_for :users  
 
  resources :cspaces

  root 'top_pages#home'
  get "home" => "top_pages#home"
  get "citizens" => "top_pages#citizens"
  get "spaces_page" => "top_pages#spaces_page"
  get "about" => "top_pages#about"
  get "find" => "top_pages#find"
  get "list" => "top_pages#list"
  get "resources" => "top_pages#resources"
  

  

end

app/models/cspace.rb
class Cspace < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/cspaces_controller.rb
class CspacesController < ApplicationController

def index
	@cspaces = Cspace.all
	#puts @cspaces
end

def show

end

def new
    @cspace = Cspace.new
end

def create

end

def edit

end

def update

end

def destroy

end





end

app/controllers/top_pages_controller.rb
class TopPagesController < ApplicationController
  def home
  end

  def citizens
  end

  def spaces_page
  end

  def about
  end

  def find
  end

  def list
  end

  def resources
  end

  def sign_in
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cspaces_helper.rb
module CspacesHelper
end

app/helpers/top_pages_helper.rb
module TopPagesHelper
end

app/views/cspaces/index.html.haml
%table.table.table--bordered.table--striped.table--linked
  %thead
    %tr
      %th Space
      %th Sq Feet
      %th Phone
      %th Type
      %th Max Occupants
      %th Owner
      %th
  %tbody
    - @cspaces.each do | space |
    %tr(data-link="#{edit_cspace_path cspace}")
      %td= cspace.space_type
      %td= cspace.id
      %td= cspace.square_feet
      %td= cspace.phone
      %td= cspace.space_type
      %td= cspace.maximum_occupants
      %td= cspace.space_type

app/views/cspaces/index.html.slim
table.table.table-bordered.table-striped
  thead
    tr
      th Id
      th Sq Feet
      th Type
      th Lease
      th FoodBeverage
      th Alcohol
      th MusicNoise
      th WIFI
      th Parking
      th Handicap
      th Max Occupants
  tbody
    tr
      td
        - @cspaces.each do | space |
          = space.id
          = space.square_feet
          = space.lease_length
          = space.food_beverage
          = space.alcohol
          = space.music_noise
          = space.wifi
          = space.parking
          = space.handicap
          = space.maximum_occupants        

app/views/cspaces/new.html.erb
<%= form_for @cspace do |f| %>
  
  <%= f.label "Address" %>:
  <%= f.text_field :address1 %><br/>
  
  <%= f.label "City" %>:
  <%= f.text_field :address2 %><br/>

  <%= f.label "Latitude" %>:
  <%= f.text_field :latitude %><br/>
  
  <%= f.label "Longitude" %>:
  <%= f.text_field :longitude %><br/>

  <%= f.label "Square Feet" %>:
  <%= f.text_field :address1 %><br/>
  
  <%= f.label "Phone" %>:
  <%= f.text_field :phone %><br/>

  <%= f.label "Space Type" %>:
  <%= f.text_field :space_type %><br/>
  
  <%= f.label "Max Occupants" %>:
  <%= f.text_field :maximum_occupants %><br/>
  
  <%= f.label "Lease Length" %>:
  <%= f.text_field :lease_length %><br/>
  
  <%= f.label "Food Beverage" %>:
  <%= f.text_field :food_beverage %><br/>

  <%= f.label "Alcohol" %>:
  <%= f.text_field :alcohol %><br/>
  
  <%= f.label "Music Noise" %>:
  <%= f.text_field :music_noise %><br/>

  <%= f.label "WIFI" %>:
  <%= f.text_field :wifi %><br/>
  
  <%= f.label "Parking" %>:
  <%= f.text_field :parking %><br/>

  <%= f.label "Handicap" %>:
  <%= f.text_field :handicap %><br/>
  
  <%= f.label "Furnished" %>:
  <%= f.text_field :furnished %><br/>

  <%= f.label "Bathroom" %>:
  <%= f.text_field :bathroom %><br/>
  
  <%= f.label "Kitchen" %>:
  <%= f.text_field :kitchen %><br/>

  <%= f.label "Photo URL" %>:
  <%= f.text_field :photo_url %><br/>
  
  <%= f.label "Photo Caption" %>:
  <%= f.text_field :photo_caption %><br/>

  <%= f.submit %>
<% end %>

app/views/cspaces/new.html.slim
= form_for @cspace do |f|
  
  .field
    = f.label "Address"
    = f.text_field :address1

  .field
    = f.label "City"
    = f.text_field :address2

  .field
    = f.label "Latitude"
    = f.text_field :latitude
  
  .field
    = f.label "Longitude"
    = f.text_field :longitude

  h2 Size and Type

  .field
    = f.label "Square Feet"
    = f.text_field :address1
  
  .field
    = f.label "Space Type"
    = f.text_field :space_type
  
  .field
    = f.label "Max Occupants"
    = f.text_field :maximum_occupants
  
  .field
    = f.label "Lease Length"
    = f.text_field :lease_length
  
  h2 Allowed Uses
  
  .field
    = f.label :food_beverage
    = f.check_box :food_beverage, :value => "1"

  /.field
  /  = f.label "Food Beverage"
  /  = f.text_field :food_beverage

  .field
    = f.label "Alcohol"
    = f.text_field :alcohol
  
  .field
    = f.label "Music Noise"
    = f.text_field :music_noise

  h2 Amenities

  .field
    = f.label "WIFI"
    = f.text_field :wifi
  
  .field
    = f.label "Parking"
    = f.text_field :parking

  .field
    = f.label "Handicap"
    = f.text_field :handicap
  
  .field
    = f.label "Furnished"
    = f.text_field :furnished

  .field
    = f.label "Bathroom"
    = f.text_field :bathroom
  
  .field
    = f.label "Kitchen"
    = f.text_field :kitchen

  h2 Photos and Description

  .field
    = f.label "Photo URL"
    = f.text_field :photo_url
  
  .field
    = f.label "Photo Caption"
    = f.text_field :photo_caption

  div align="center"
    .actions = f.submit 'Save'

app/views/layouts/_footer.html.erb
<footer class="footer"
  <p>Other Resources  |  Privacy Policy  | Terms & Conditions</p>
</footer>

app/views/layouts/_messages.html.erb
<% flash.each do | name, msg | %>
  <% if msg.is_a?(String) %>
    <%= content_tag :div, msg, :id +> "flash_#{name}" %>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%= link_to "Civicspaces", root_path, :class => 'brand' %>
<ul class="nav">
	<% if user_signed_in? %>
	  <li>
	    <%= link_to 'logout', destroy_user_sessio_path, :method => 'delete' %>
	  </li>
	<% else %>
	  <li>
	    <%= link_to 'login', new_user_session_path %>
	  </li>
	<% end %>
  <% if user_signed_in? %>
    <li>
    	<%= link_to 'Edit account', edit_user_registration_path %>
    </li>
  <% else %>
    <li>
    	<%= link_to 'Sign up', new_user_registration_path %>
    </li>
  <% end %>
</ul>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta name="viewport" content="width=device-width, initial-scale=1.0")
  <title>CivicSpaces | <%= yield(:title) %></title>
  <%= stylesheet_link_tag    "application", media: "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <%= render 'layouts/shim' %>
</head>
<body>
  <header class="navbar navbar-fixed-top">
  	<div class="navbar-inner">
  	  <% link_to "CivicSpaces", '#', id: "logo" %>
  	  <nav>
  	  	<ul class="nav pull-right">
          <li><%= link_to "Home",       home_path      %></li>
  	      <li><%= link_to "About",      about_path     %></li>
  	      <li><%= link_to "Citizens",   citizens_path  %></li>
          <li><%= link_to "Resources",  resources_path %></li>
          <li><%= link_to "Find",       find_path      %></li>
          <li><%= link_to "List",       list_path      %></li>
  	    </ul>
  	  </nav>
  	</div>
  </header>
  <div class="container">
	  <%= yield %>
    <%= render 'layouts/footer' %>
  </div>
</body>
</html>

app/views/top_pages/about.html.erb
<h1>About</h1>
<p>
CivicSpaces is a site to help active citizens, artists and nonprofits find unused spaces to host their events an ddisplay their crative work. We serve as a conduit, connecting owners of empty spaces with people who want to fill them for a shorty-term project, event or activity.

Building owners who have vacant storefronts, office space or even empty lots can offer their space through CivicSpaces to attract artists and nonprofits to fill them with life for a short time period.

There are many studies showing that active spaces are more attractive and easier to rent than empty ones. Additionally having active offices and storefronts can lead to increased foot traffic, increase an areas visibility and reducing crime. We want to keep our city vibrant, one empty space at a time.
</p>

app/views/top_pages/citizens.html.erb
<h1>Citizens</h1>
<p>Individuals and organizations like you constantly need space to grow ideas. Office space to work in. Event space for fundraisers. A vacant lot to grow food on. CivicSpaces can pair you with empty properties around Atlanta. We allow you to find properties that fit your needs, location, size and use and best of all that fit your budget. Our participating spaces range from free to medium rental costs. Search our database, find a property that matches your need and connect!</p>

app/views/top_pages/find.html.erb
<h1>Find</h1>
<p>This is where you go to find a space</p>
<%= image_tag("sleekoffice.jpeg", :alt => "") %>

app/views/top_pages/home.html.erb
<% provide(:title, 'Home') %>
<h1>Welcome to CivicSpaces</h1>
<h2>a way to connect active citizens to unused spaces in the city.</h2>
<%= image_tag("officeabstract.jpeg", :alt => "") %>
<h2> Find a space to grow your idea or event!
<h3>Community groups can search for and connect with empty offices, storefronts or even vacant lots and fill them with their events and activites. Spaces range from free to medium in cost and vary in neighborhood, size and  functionality.
<%= image_tag("officemanydesks.jpeg", :alt => "") %>

app/views/top_pages/list.html.erb
<h1>List</h1>
<p>This is to enter you space in the system</p>
<%= image_tag("longtable.jpeg", :alt => "") %>

app/views/top_pages/resources.html.erb
<h1>Resources</h1>
<p>This page is for additional resources you may find useful</p>

app/views/top_pages/spaces.html.erb
<h1>Spaces</h1>
<p>This is the spaces page</p>
<%= image_tag("office_lobby1.jpg", :alt => "") %>

app/views/top_pages/spaces_page.html.erb
<h1>Spaces</h1>
<p>This is the spaces page</p>
<%= image_tag("office_lobby1.jpg", :alt => "") %>